# Generated by Django 5.1.2 on 2024-10-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('analysis_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='analysis_app.analysissummary')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
                ('analysis_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_data', to='analysis_app.analysissummary')),
            ],
        ),
    ]
