# Generated by Django 5.1.2 on 2024-10-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='value',
            field=models.TextField(),
        ),
    ]
